#CSC Computer Science 2
#Lab 13: Pig Latin Strings
#Programmers: Mike and Andrew
#Professor: Dr. Lee
#File Created: April 13, 2017
#File Updated: April 13, 2017

SOURCES = lab13.c
OBJECTS = lab13.o
HEADERS = lab13.h
CC = gcc
CFLAGS = -g -Wall

lab13: $(OBJECTS)
	$(CC) $(CFLAGS) $(SOURCES) -o lab13
clean:
	rm -fR *o lab13
