#Lab 16: makefile
#Programmer: Andrew S and Mike S
#Class: CS2
#Professor: Dr. Lee
#File Created: April 25, 2017
#File Updated: April 25, 2017

all: airmile

clean:
	rm -f airmile
airmiles: airmile.c
	gcc -o airmiles airmile.c
