# CSC111 Computer Science 2
# Lab 10: Advanced Function Pointers
# Programmers: Shane A. & Andrew S.
# Professor: Dr. Lee
# File Created: March 28, 2017
# File Updated: March 28, 2017

all: p455n15 p455n16

clean:
	rm -f p455n15 p455n16

p455n15: p455n15.c
	cc -o p455n15 p455n15.c

p455n16: p455n16.c
	cc -o p455n16 p455n16.c
